print ("Albert Elías Arason")
print ("140600-3180")
print("")
print("")
print ("#################")
print ("# Ég er svnagur #")
print ("#################")
print("")
print("")
print ("###################")
print("")
print ("Ég er ennþá svangur")
print("")
print ("###################")
print("")
print ('"Halló Heimur"')
print
print (" 'Halló Helgi' ")